name: Build and Deploy Docker app to Azure Web App - smartSK-backend

on:
push:
branches:
- main
workflow_dispatch:

jobs:
build-and-deploy:
runs-on: ubuntu-latest
permissions:
contents: read
id-token: write

steps:
  - name: Checkout code
    uses: actions/checkout@v4

  - name: Login to Azure using OIDC
    uses: azure/login@v2
    with:
      client-id: 3cf53574-bca2-498b-bef8-302f807b6472
      tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
      subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

  - name: Build and Push Docker image
    run: |
      IMAGE_NAME=smartskregistry.azurecr.io/smartsk-backend
      GIT_SHA=${{ github.sha }}

      echo "Building Docker image..."
      docker build --no-cache -t $IMAGE_NAME:$GIT_SHA -t $IMAGE_NAME:latest ./backend

      echo "Pushing Docker image..."
      docker push $IMAGE_NAME:$GIT_SHA
      docker push $IMAGE_NAME:latest

  - name: Deploy to Azure Web App
    run: |
      az webapp config container set \
        --name smartsk-backend-container \
        --resource-group Smart_SK \
        --docker-custom-image-name smartskregistry.azurecr.io/smartsk-backend:latest